###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: Push Nuget Packages and Tag

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0']
    steps:
    - name: Checkout code
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src --configuration Release --no-restore

    - name: Check Package Suffix Versions
      shell: bash
      run: |
        script_output=$(./scripts/no_suffix_version_check.sh)

        if [ -z "$script_output" ]; then
          echo "No version suffixes set"
        else
          echo "the following packages have a suffix version set, please remove them:"
          echo "$script_output"
          exit 1
        fi

    - name: Push nuget packages
      shell: bash
      run: |
        bash ./scripts/pack_and_push_packages.sh --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Get new version
      id: nugetPackageVersion
      shell: bash
      run: |
        current_version=$(./scripts/get_current_version.sh)
        echo "version=$current_version" >> "$GITHUB_OUTPUT"

    - name: Create git tag
      uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72 # v1.7.2
      with:
        tag: ${{ steps.nugetPackageVersion.outputs.version }}
