###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: "Veracode"

on:
  #  push:
  #    branches: [main]
  # pull_request:
  # The branches below must be a subset of the branches above
  # branches: [ main ]
  # paths-ignore:
  #   - "**/*.md"
  #   - "**/*.txt"
  # Trigger manually
  workflow_dispatch:
  # Triggered once a week
  schedule:
   - cron: "0 0 * * 0"


env:
  DOTNET_VERSION: '6.0' # The .NET SDK version to use

jobs:
  analyze-administration-service:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/administration/Administration.Service

      - name: Build and publish
        run: |
          cd src/administration/Administration.Service
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-administration-service.zip
          src/administration/Administration.Service/.publish
          -x
          src/administration/Administration.Service/.publish/Org.Eclipse.TractusX.Portal.Backend.Administration.Service

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Administration-Service"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-administration-service.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.Portal.Backend.Administration.Service.dll'

  analyze-registration-service:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/registration/Registration.Service

      - name: Build and publish
        run: |
          cd src/registration/Registration.Service
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-registration-service.zip
          src/registration/Registration.Service/.publish
          -x
          src/registration/Registration.Service/.publish/Org.Eclipse.TractusX.Portal.Backend.Registration.Service

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Registration-Service"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-registration-service.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.Portal.Backend.Registration.Service.dll'

  analyze-provisioning-service:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/provisioning/Provisioning.Service

      - name: Build and publish
        run: |
          cd src/provisioning/Provisioning.Service
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-provisioning-service.zip
          src/provisioning/Provisioning.Service/.publish
          -x
          src/provisioning/Provisioning.Service/.publish/Org.Eclipse.TractusX.Portal.Backend.Provisioning.Service

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Provisioning-Service"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-provisioning-service.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.Portal.Backend.Provisioning.Service.dll'

  analyze-marketplace-app-service:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/marketplace/Apps.Service

      - name: Build and publish
        run: |
          cd src/marketplace/Apps.Service
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-marketplace-app.zip
          src/marketplace/Apps.Service/.publish
          -x
          src/marketplace/Apps.Service/.publish/Org.Eclipse.TractusX.Portal.Backend.Apps.Service

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Marketplace-App-Service"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-marketplace-app.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.Portal.Backend.Apps.Service.dll'

  analyze-portal-migrations:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/portalbackend/PortalBackend.Migrations

      - name: Build and publish
        run: |
          cd src/portalbackend/PortalBackend.Migrations
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-portal-migrations.zip
          src/portalbackend/PortalBackend.Migrations/.publish

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Portal-Migrations-Service"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-portal-migrations.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.Portal.Backend.PortalBackend.Migrations.dll'

  analyze-maintenance-service:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/maintenance/Maintenance.App

      - name: Build and publish
        run: |
          cd src/maintenance/Maintenance.App
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-maintenance-service.zip
          src/maintenance/Maintenance.App/.publish

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Maintenance-Service"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-maintenance-service.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.Portal.Backend.Maintenance.App.dll'

  analyze-notification-service:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/notifications/Notifications.Service

      - name: Build and publish
        run: |
          cd src/notifications/Notifications.Service
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-notification.zip
          src/notifications/Notifications.Service/.publish
          -x
          src/notifications/Notifications.Service/.publish/Org.Eclipse.TractusX.Portal.Backend.Notifications.Service

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Notification-Service"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-notification.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.Portal.Backend.Notifications.Service.dll'

  analyze-services-service:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/marketplace/Services.Service

      - name: Build and publish
        run: |
          cd src/marketplace/Services.Service
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-services.zip
          src/marketplace/Services.Service/.publish
          -x
          src/marketplace/Services.Service/.publish/Org.Eclipse.TractusX.Portal.Backend.Services.Service

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Services-Service"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-services.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.Portal.Backend.Services.Service.dll'

  analyze-provisioning-migrations:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/provisioning/Provisioning.Migrations

      - name: Build and publish
        run: |
          cd src/provisioning/Provisioning.Migrations
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-provisioning-migrations.zip
          src/provisioning/Provisioning.Migrations/.publish

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Provisioning-Migrations-Service"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-provisioning-migrations.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.CatenaX.Ng.Portal.Backend.Provisioning.Migrations.dll'

  analyze-checklist-worker:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/processes/Processes.Worker

      - name: Build and publish
        run: |
          cd src/processes/Processes.Worker
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r portal-backend-checklist-worker.zip
          src/processes/Processes.Worker/.publish

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Portal-Backend_Checklist-Worker"
          createprofile: true
          teams: 'portal'
          # Specify path to upload
          filepath: "portal-backend-checklist-worker.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.Portal.Backend.Processes.Worker.dll'
